drawings_show/urls.py
from django.conf.urls import url

import views
from views import RevisionsView, SectionsStatisticsView


urlpatterns = (
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^show/$', views.show, name='show'),
    url(r'^add/$', views.add_drawing, name='add_drawing'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^find/$', views.find_drawing, name='find_drawing'),
    url(r'^drawing/(?P<drawing_id>\d+)/$', RevisionsView.as_view(), name='show_drawing'),
    url(r'^revision/(?P<revision_id>\d+)/$', views.edit_revision, name='edit_revision'),
    url(r'^stats/$', SectionsStatisticsView.as_view(), name='show_stats'),
    url(r'^report/$', views.get_report, name='get_report'),
)

mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from admin import admin_site


urlpatterns = [
    url(r'^admin/', include(admin_site.urls)),
    url(r'^drawings/', include('drawings_show.urls')),
    url(r'^$', include('drawings_show.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'drawings_show/login.html'}, name='login'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drawings_show/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.timezone import now


def normalize_number(number):
    return number.replace(' ', '_').replace('.', '_').replace('-', '_')


class Drawing(models.Model):
    number = models.CharField(max_length=200, verbose_name=u'Шифр проекта')
    page = models.CharField(max_length=20, verbose_name=u'Лист')
    normalized_number = models.CharField(max_length=200,
                                         blank=True,
                                         editable=False,
                                         verbose_name='Нормализованный шифр проекта')

    def save(self, *args, **kwargs):
        self.number = self.number.replace(" ", "_")
        self.normalized_number = normalize_number(self.number)
        super(Drawing, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('show_drawing', kwargs={'drawing_id': self.pk})

    def __unicode__(self):
        return u"%s, лист %s." % (self.number, self.page)

    class Meta:
        unique_together = ('number', 'page')
        verbose_name = 'чертеж'
        verbose_name_plural = 'чертежи'


class Revision(models.Model):
    drawing = models.ForeignKey(Drawing, verbose_name='Чертеж')
    name = models.CharField(max_length=1000, verbose_name=u'Наименование чертежа')
    number = models.IntegerField(verbose_name=u'Номер изма')
    date = models.DateField(default=now, verbose_name=u'От')
    is_deleted = models.BooleanField(default=False, verbose_name=u'Удален')
    cover_letter_number = models.CharField(max_length=100,
                                           blank=True,
                                           verbose_name=u'Номер сопроводительного')

    def __unicode__(self):
        if self.number == -1:
            rev = "Аннулировано"
        else:
            rev = u". изм.%i " % self.number if self.number != 0 else ""
        return u"%s %s%s от %s" % (self.drawing, self.name, rev, self.date)

    class Meta:
        verbose_name = 'ревизия чертежа'
        verbose_name_plural = 'ревизии чертежей'


class DrawingQuery(models.Model):
    number = models.CharField(max_length=200, verbose_name=u'Шифр проекта')
    page = models.CharField(max_length=20, verbose_name=u'Лист')
    revision = models.IntegerField(verbose_name=u'Номер изма')
    timestamp = models.DateTimeField(verbose_name=u'Время запроса', auto_now_add=True)

    class Meta:
        verbose_name = 'запрос чертежа'
        verbose_name_plural = 'запросы чертежей'

drawings_show/forms.py
# -*- coding: utf8 -*-
from django import forms


class FindDrawingForm(forms.Form):
    number = forms.CharField(required=True, label=u'Шифр')
    page = forms.IntegerField(required=True, label=u'Лист')

    def __init__(self, *arg, **kwarg):
        super(FindDrawingForm, self).__init__(*arg, **kwarg)
        self.empty_permitted = False

drawings_show/views.py
# -*- coding: utf8 -*-
from django.shortcuts import render_to_response, get_object_or_404, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse
from django.db.models import Count

from django.views.generic import ListView, UpdateView, DetailView, TemplateView, RedirectView
from django.utils.decorators import method_decorator

from models import Drawing, Revision, DrawingQuery
from models import normalize_number
from forms import FindDrawingForm
from datetime import date


class RevisionRedirectView(RedirectView):
    pass


class RevisionsView(ListView):
    model = Revision

    def get_queryset(self):
        return self.drawing.revision_set.all()

    @method_decorator(login_required())
    def dispatch(self, request, *args, **kwargs):
        drawing_id = kwargs['drawing_id']
        self.drawing = Drawing.objects.get(pk=drawing_id)
        return super(RevisionsView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(RevisionsView, self).get_context_data(**kwargs)
        context['drawing'] = self.drawing
        return context


class SectionsStatisticsView(ListView):
    model = Drawing
    template_name = 'drawings_show/sections_stats.html'

    def __init__(self, *args, **kwargs):
        super(SectionsStatisticsView, self).__init__(*args, **kwargs)

    def get_queryset(self):
        qs = Drawing.objects.values('number').annotate(ncount=Count('number'))
        return qs

    @method_decorator(login_required())
    def dispatch(self, request, *args, **kwargs):
        return super(SectionsStatisticsView, self).dispatch(request, *args, **kwargs)


class RevisionChangeState(UpdateView):
    model = Revision


class IndexView(TemplateView):
    template_name = 'drawings_show/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['count'] = Revision.objects.count()
        return context


class RevisionDetail(DetailView):
    model = Revision
    template_name = 'drawings_show/show_drawing_status.html'

    def dispatch(self, request, *args, **kwargs):
        revision = self.get_object()
        drawing = revision.drawing
        DrawingQuery.objects.create(number=drawing.number, page=drawing.page, revision=revision.number)
        return super(RevisionDetail, self).dispatch(request, *args, **kwargs)


# =============================================================================
# Views
# =============================================================================
def show(request):
    req = request.GET or None
    number = req.get('number', '')
    page = req.get('page', '')
    rev = req.get('revision', '')

    DrawingQuery.objects.create(number=number, page=page, revision=rev)
    normalized_number = normalize_number(number)

    # TODO: Исправить это! Сейчас берётся непонятно какой чертеж
    drawing = Drawing.objects.filter(normalized_number=normalized_number,
                                     page=page)
    if drawing:
        drawing = drawing[0]
    else:
        return drawing_not_found(request)

    if drawing.revision_set.exclude(is_deleted=True).order_by('-number'):
        last_revision = drawing.revision_set.exclude(is_deleted=True).order_by('-number')[0]
        first_revision = drawing.revision_set.exclude(is_deleted=True).order_by('number')[0]
    else:
        return drawing_not_found(request)
    try:
        if first_revision.number == -1:
            revision = first_revision
        else:
            revision = drawing.revision_set.get(number__exact=rev, is_deleted=False)
    except Revision.DoesNotExist:
        return revision_not_found(request, drawing)

    return render_to_response('drawings_show/show_drawing_status.html', {
        'drawing': drawing,
        'revision': revision,
        'last_revision': last_revision,
    })

# @login_required
@csrf_exempt
def add_drawing(request):
    if request.POST:
        req = request.POST

        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = authenticate(username=username, password=password)
        if user and user.is_active:
            login(request, user)

            number = req['number']
            page = req['page']
            name = req['name']
            rev = req['revision']
            date = req['date']
            cover_letter_number = req.get('cover_letter_number', '')
            normalized_number = normalize_number(number)
            try:
                drawing = Drawing.objects.get(normalized_number=normalized_number, page=page)
            except Drawing.DoesNotExist:
                drawing = Drawing.objects.create(number=number, page=page)
            if not drawing.revision_set.filter(number__exact=rev, is_deleted__exact=False).exists():
                Revision.objects.create(drawing=drawing,
                                        number=rev,
                                        date=date,
                                        name=name,
                                        cover_letter_number=cover_letter_number)
                message = "Чертеж добавлен успешно"
            else:
                message = "Ошибка! Данный чертеж уже есть в базе!"
        else:
            message = "Ошибка! Ошибка авторизации!"
    else:
        message = "Error! Request didn't found"
    return HttpResponse(message)


@login_required
def find_drawing(request):
    find_form = FindDrawingForm(request.GET or None)
    if request.GET:
        if find_form.is_valid():
            drawing = get_object_or_404(Drawing, number__exact=request.GET["number"], page__exact=request.GET["page"])
            return HttpResponseRedirect(reverse('show_drawing', args=(drawing.pk,)))

    return render(
        request,
        'drawings_show/find_drawing.html', {
            'find_form': find_form,
        })


@login_required
def edit_revision(request, revision_id):
    revision = get_object_or_404(Revision, pk=revision_id)
    drawing = revision.drawing

    if request.GET:
        drawing_id = request.GET.get("drawing_id", None)

    elif request.POST:
        drawing_id = request.POST.get("drawing_id", None)
        if "delete" in request.POST:
            revision.is_deleted = True
        elif "restore" in request.POST:
            revision.is_deleted = False
        revision.save()
        return HttpResponseRedirect(reverse("show_drawing", args=(drawing.pk,)))

    return render(
        request,
        'drawings_show/edit_revision.html', {
            'drawing_id': drawing_id,
            'revision': revision,
        })


@login_required
def get_report(request):
    from excel_manipulations import create_drawings_report
    revisions = Revision.objects.filter(is_deleted__exact=False)
    rep = create_drawings_report(revisions)
    response = HttpResponse(rep, content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    filename = "report %s.xlsx" % date.today()
    response['Content-Disposition'] = 'attachment; filename="%s"' % filename
    return response


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("drawings.drawings_show.views.index"))


def drawing_not_found(request):
    """ Обработка отсутствующего документа """
    req = request.GET or None
    number = req.get('number', '')
    page = req.get('page', '')
    rev = req.get('revision', '')
    if not number:
        error_message = u'Не указан шифр чертежа!'
    elif not page:
        error_message = u'Не указан номер листа!'
    elif not rev:
        error_message = u'Не указан номер изменения!'
    else:
        error_message = u"Ошибка! Не найден чертеж: %s, лист %s" % (number, page)
    return HttpResponse(error_message)


def revision_not_found(request, drawing):
    """Обработка отсутствующей ревизии"""
    req = request.GET or None

    rev = req.get('revision', '')
    if not rev:
        error_message = u'Не указан номер изменения!'
    else:
        error_message = u"Ошибка! Не найдено изменение %s чертежа: %s, лист %s" % (rev, drawing.number, drawing.page)
        error_message += u"<br/>В базе сохранены данные о следующих изм'ах"
        for r in drawing.revision_set.order_by('number'):
            error_message += u"<br/>%s" % unicode(r)

    return HttpResponse(error_message)


def handler404(request):
    req = request.GET or None
    number = req.get('number', '')
    name = req.get('name', '')
    page = req.get('page', '')
    rev = req.get('revision', '')
    d = u"%s, лист %i. %s" % (number, page, name)
    r = u". изм.%i " % rev if rev != 0 else ""
    drawing = u"%s%s" % (d, r)
    return render_to_response('404.html', {
        'drawing': drawing,
    })


def handler500(request):
    pass

drawings_show/templates/drawings_show/auth.html
{% extends "base.html" %}

{% block auth %}
        <div class="pull-right">
            {% if user.is_authenticated %}
                Вы зашли под пользователем: {{ user.username }}<br/>
                <a href="{% url 'user_logout' %}">Выйти</a>
            {% else %}
                Для работы необходимо войти в систему!<br/>
                <a href="{% url 'login' %}">Войти</a>
            {% endif %}
        </div>
        <div class="left">
            <a href="{% url 'find_drawing' %}">Поиск чертежей</a>
        </div>
    <hr/>
{% endblock %}
{% block content %}
{% endblock %}

drawings_show/templates/drawings_show/edit_revision.html
{% extends "drawings_show/auth.html" %}

{% block title %}
Редактирование изма
{% endblock %}

{% block content %}
<form method="post" action="{% url 'edit_revision' revision.pk %}">
{% csrf_token %}
    <table>
        <caption>
            Изменение состояния версии чертежа
        </caption>
        <thead>
            <tr>
                <th>Чертеж</th>
                <th>Активен?</th>
                <th>Изменить состояние</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ revision }}</td>
                <td>{{ revision.is_deleted|yesno:"Нет,Да" }}</td>
                <td>
                    {% if not revision.is_deleted %}
                        <input type="submit" name="delete" value="Удалить" />
                    {% else %}
                        <input type="submit" name="restore" value="Восстановить" />
                    {% endif %}
                </td>
            </tr>
        </tbody>
    </table>
    <a href="{% url 'show_drawing' drawing_id %}">Назад</a>
    <input type="hidden" name="drawing_id" value="{{ drawing_id }}" />
</form>
{% endblock %}

drawings_show/templates/drawings_show/find_drawing.html
{% extends "drawings_show/auth.html" %}

{% block title %}
Поиск чертежа
{% endblock %}

{% block content %}
<div class="span-18 prepend-3">
    <form id="filter" method="get" action="{% url 'find_drawing' %}">
        <table>
            <caption>
                Поиск чертежа
            </caption>
        {{ find_form.as_table }}
        </table>
        <input type="submit" name="submit" value="Поиск" />
    </form>
</div>
{% endblock content %}

drawings_show/templates/drawings_show/index.html
{% extends "base.html" %}

{% block title %}
Основная страница
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h1>Актуальность чертежей ООО&nbsp;"Проектное бюро-ГС"</h1>
            <p>В базе зарегистрировано чертежей: <span class="label label-success">{{ count }}</span></p>
{#            {% if user.is_authenticated  %}#}
{#                <p>#}
{#                    <a class="btn btn-primary btn-lg">Learn more</a>#}
{#                </p>#}
{#            {% endif %}#}
        </div>
    </div>
{% endblock %}

drawings_show/templates/drawings_show/login.html
{% extends "base.html" %}

{% block content %}

    {% if form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            Логин или пароль не подходят. Попробуйте ещё раз
        </div>
    {% endif %}

    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>
        <input type="submit" value="Вход" />
        <input type="hidden" name="next" value="{{ next|default:'/' }}" />
    </form>

{% endblock content %}

drawings_show/templates/drawings_show/revision_list.html
{% extends "drawings_show/auth.html" %}

{% block title %}
Список измов
{% endblock %}

{% block content %}
<table>
    <caption>
        Список версий чертежа
    </caption>
    <thead>
        <tr>
            <td>#</td>
            <th>Шифр чертежа</th>
            <th>Наименование чертежа</th>
            <th>Изм.</th>
            <th>Дата</th>
            <th>Номер сопроводительного</th>
            <th>Активен?</th>
        </tr>
    </thead>
    <tbody>
        {% for revision in revision_list %}
        {% url 'edit_revision' revision.pk as edit_url %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{{ edit_url }}?drawing_id={{ drawing.id }}">{{ drawing.number }}</a></td>
            <td>{{ revision.drawing.name }}</td>
            <td>{{ revision.number|default:"-" }}</td>
            <td>{{ revision.date }}</td>
            <td>{{ revision.cover_letter_number }}</td>
            <td><a href="{{ edit_url }}?drawing_id={{ drawing.id }}">{{ revision.is_deleted|yesno:"Нет,Да" }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

drawings_show/templates/drawings_show/sections_stats.html
{% extends "drawings_show/auth.html" %}

{% block title %}
Статистика
{% endblock %}

{% block content %}
<table>
    <caption>Статистика по разделам</caption>
    <thead>
        <tr>
            <th></th>
            <th>Шифр</th>
            <th>Кол-во чертежей</th>
        </tr>
    </thead>
    <tbody>
        {% for drawing in drawing_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ drawing.number }}</td>
                <td>{{ drawing.ncount }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

drawings_show/templates/drawings_show/show_drawing_status.html
{% extends 'base.html' %}

{% block title %}
Проверка статуса
{% endblock %}

{% block content %}
    <table class="table table-bordered">
        <caption>Актуальность чертежа:</caption>
        <thead>
        <tr>
            <th>
                Актуальность
            </th>
            <th>
                Шифр чертежа
            </th>
            <th>
                Наименование
            </th>
            {% if revision.number > 0 %}
                <th>
                    Изм.
                </th>
            {% endif %}
            <th>
                Дата выпуска
            </th>
            {% if revision.cover_letter_number %}
                <th>Сопроводительное письмо</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        <tr>
            <td id="status">
                {% if revision.number == -1 %}
                    Чертеж аннулирован
                {% else %}
                    {% if revision == last_revision %}
                        <span class="label label-success">Актуален</span>
                    {% else %}
                        <span class="label label-danger">Не актуален</span>
                    {% endif %}
                {% endif %}
            </td>
            <td>
                {{ drawing }}
            </td>
            <td>
                {{ revision.name }}
            </td>
            {% if revision.number > 0 %}
                <td>
                    {{ revision.number }}
                </td>
            {% endif %}
            <td>
                {{ revision.date }}
            </td>
            {% if revision.cover_letter_number %}
                <td>
                    {{ revision.cover_letter_number }}
                </td>
            {% endif %}
        </tr>
        </tbody>
    </table>
    {% if revision != last_revision %}
        <p class="text-danger">Последняя версия данного чертежа: {{ last_revision }}</p>
    {% endif %}
{% endblock %}